version: '3.1'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db_nest
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./vols/postgres/data:/var/lib/postgresql/data
      - ./vols/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql